### ISSUE TITLE
Is Anyone Working on a QGIS Interface?

### ISSUE THREAD

**Issue by hamiltoncj** [scikit-mobility/scikit-mobility#103]
I have been considering working on a QGIS interface for this library, but wanted to check to see if anyone else was planning on doing it.

How serious are you in developing this library? There are a lot of issues in your queue. It could mean that there is a lot of interest or that the developers don't have the funding or time to keep up.

It appears that this library has a lot of potential so I hope it is going to be well supported.

Thanks

**Comment by jonpappalord** [comment]
> I have been considering working on a QGIS interface for this library, but wanted to check to see if anyone else was planning on doing it.

As far as we know, there is no active project on creating a QGIS interface for scikit, yet.

> How serious are you in developing this library? There are a lot of issues in your queue. It could mean that there is a lot of interest or that the developers don't have the funding or time to keep up.

The library received a lot of attention in the recent period, so we are now in the process of implementing the issues suggested by the users. scikit-mobility is and will remain an active project for the next years since its development is part of a bigger project funded by the EU.
