### ISSUE TITLE
Installation Issue in skmob environment Jupyter Notebook

### ISSUE THREAD

**Issue by Dhanesh-raj** [scikit-mobility/scikit-mobility#153]
(base) dhaneshraj@dhaneshraj-HP-2000-Notebook:~$ source activate skmob
(skmob) dhaneshraj@dhaneshraj-HP-2000-Notebook:~$ conda install -c conda-forge scikit-mobility
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): |

How can I install scikit-mobility

**Comment by jonpappalord** [comment]
we noticed that, when installing with conda-forge, sometimes the installation freezes at "solving environment". We think this is a problem related to conda-forge rather than to scikit-mobility, we are investigating it deeply. 

If the installation with ``conda install -c conda-forge scikit-mobility`` does not work, try to install the library using ``pip install scikit-mobility``
