### ISSUE TITLE
EPR: the speed of the script depends on previous generations

### ISSUE THREAD

**Issue by denadai2** [scikit-mobility/scikit-mobility#59]
Dear all,
is it normal that the speed of the computation increases agent per agent? It is strange that in the first agent the script takes 4 second, while in the 1000s it takes only milliseconds. Is it normal?

Example with 200 agents

![Screenshot 2019-11-21 at 16 23 19](https://user-images.githubusercontent.com/190799/69351250-48327b00-0c7b-11ea-9298-1731626c093c.png)

![Screenshot 2019-11-21 at 16 23 25](https://user-images.githubusercontent.com/190799/69351254-4c5e9880-0c7b-11ea-868c-ed4cdebc4335.png)

thx

**Comment by jonpappalord** [comment]
In the DensityEPR model, an agent's decision on where to go next when exploring relies on the values in an origin-destination matrix `OD`, which contains the probability of moving from one location to another on the spatial tessellation. Initially, `OD` is "empty" and it is populated as the simulation goes by. Specifically, every time a new location is explored, the corresponding row in `OD` is empty (i.e., all zeros), so the probabilities must be computed. The computation of the probabilities for a location is linear in the number of locations in the spatial tessellation. Since the same `OD` is used for all the agents, as the simulation goes `OD` is more and more populated, the access to it is constant and the simulation speeds up.
